[package]
name = "bvh"
description = "A fast BVH using SAH"
version = "0.3.0"
edition = "2018"
authors = [
    "Sven-Hendrik Haase <svenstaro@gmail.com>",
    "Alexander Dmitriev <alexander.dmitriev2580@gmail.com>"
]
readme = "README.md"
repository = "https://github.com/svenstaro/bvh"
documentation = "https://docs.rs/crate/bvh"
keywords = ["bvh", "bounding", "volume", "sah", "aabb"]
license = "MIT"

[dependencies]
#approx = "0.3"
glam = "0.8"
rand = "0.7"
log = "0.4"

[dev-dependencies]
quickcheck = "0.8"
obj-rs = "0.4"

[features]
bench = []

[profile.release]
lto = true

[profile.bench]
lto = true
